### PR TITLE
Refactor/#25

### PR DESCRIPTION
**Pull request by louis030195**

### CODE REVIEW

**Comment by louis030195** [comment]
before merging let's run few examples 

I've ran unit test manually

**Comment by CakeCrusher** [comment]
@louis030195 
Running into an issue where having missing the optional arguments result in an error. In this case it was instructions but I'm sure this pertains to multiple fields in multiple functions.
https://github.com/stellar-amenities/assistants/blob/534145118cbd71273fbbcf6aa23cac0c2b62aae5/assistants-api-communication/src/assistants.rs#L28  

Likely related to an overly permissive structure https://github.com/stellar-amenities/assistants/blob/534145118cbd71273fbbcf6aa23cac0c2b62aae5/assistants-api-communication/src/assistants.rs#L20

**Comment by CakeCrusher** [comment]
In the process of solving that by creating a better struct you could simultaneously refractory out dependance on `async-openai` (as shown here: https://github.com/stellar-amenities/assistants/blob/534145118cbd71273fbbcf6aa23cac0c2b62aae5/assistants-api-communication/src/assistants.rs#L6-L8 ) and in its place add our own structures (as shown here https://github.com/stellar-amenities/assistants/blob/534145118cbd71273fbbcf6aa23cac0c2b62aae5/assistants-api-communication/src/assistants.rs#L5 ) this will probably be the most prudent solution.

**Comment by louis030195** [comment]
status:

using https://github.com/louis030195/async-openai which fix the open source llm compatibility

left to fix:
- some issues with function calling left - not sure yet what's the problem - maybe something with how i parse the llm answer

**Pull request closed without merging**
