### PR TITLE
Support aliyun tongyiqianwen llm as a candidate llm

### PR DESCRIPTION
**Pull request by FingerLiu**

### CODE REVIEW

**Comment by louis030195** [comment]
just noticed this after pushing a related change actually

why is that function necessary? cant we just use the open source llm function one for aliyun?

**Comment by louis030195** [comment]
i'm working towards having a better way to configure the API and thus a better way to configure the LLM API to use

would be happy to have hal-9100 compatible with `aliyun` though, with some example/doc would be also great

**Comment by FingerLiu** [comment]
Perhaps we need an intermediary protocol to convert other non-OpenAI LLM APIs into OpenAI-compatible protocols, or find an open-source project that implements a similar layer of conversion.

**Comment by louis030195** [comment]
@FingerLiu most LLM infra offer openai api style but we can implement custom integration if necessary (thinking about Google's Vertex/Gemini typically don't support OpenAI API style)

**Comment by louis030195** [comment]
@FingerLiu now news? closing

**Pull request closed without merging**
